version: '3.8'

services:
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'bookdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'bookadmin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'